from v3_0.shared.exceptions.justin_error import JustinError


class CheckFailedError(JustinError):
    pass
